Repository k8-proxy/k8-traffic-generator, pull requests merged in 2020-09, with the labels that each got.

#51 Improve Docker build
  upwork-devs/ashish-belwase/.dockerignore
  upwork-devs/ashish-belwase/Dockerfile
Labels: ready-for-review

#50 Create architecture diagrams for this project (including who is working on what)
  docs/artillery-pod.png
  docs/logio-poc.pdf
  docs/logio-workflow.pdf
  docs/traffic-for-multiple-sites-API.pdf
Labels: changes-requested, ready-for-review

#54 Use environment variables
  upwork-devs/ashish-belwase/.dockerignore
  upwork-devs/ashish-belwase/Dockerfile
  upwork-devs/ashish-belwase/README.md
  upwork-devs/ashish-belwase/docker-entrypoint.sh
  upwork-devs/ashish-belwase/main.py
  upwork-devs/ashish-belwase/tests/test_glasswall.py
  upwork-devs/ashish-belwase/tests/test_main.py
  upwork-devs/ashish-belwase/traffic_generator.py
Labels: ready-for-review

#63 allow generic multiple sites, common site loader, remove hard coded s…
  upwork-devs/ashish-belwase/helper.py
  upwork-devs/ashish-belwase/main.py
  upwork-devs/ashish-belwase/sites/__init__.py
  upwork-devs/ashish-belwase/sites/glasswall_engineering.py
  upwork-devs/ashish-belwase/traffic_generator.py
Labels: ready-for-review

#70 POC with Elastic Packetbeat as a log monitoring tool
  upwork-devs/harut-gigoryan/packetbeat-poc/README.md
  upwork-devs/harut-gigoryan/packetbeat-poc/all-in-one.yaml
  upwork-devs/harut-gigoryan/packetbeat-poc/packetbeat.yaml
Labels: ready-for-review

#72 Added a concept document for testing an API endpoint
  upwork-devs/faisal-adnan/Artillery/Dockerfile
  upwork-devs/faisal-adnan/Concept/README.md
Labels: ready-for-review

#64 Create MD (markdown) file that explains the workflow
  docs/README.md
  docs/pngs/logging-workflow.png
  docs/pngs/rebuild-api-utilization.png
  docs/pngs/traffic-for-multiple-sites-API-v2.png
  docs/pngs/traffic-generator.png
  docs/rebuild-engine-as-a-target.md
Labels: changes-requested, ready-for-review

#66 Use Gatsby to automatically generate a site from markdown
  upwork-devs/ashish-belwase/documentation_site/.github/workflows/main.yml
  upwork-devs/ashish-belwase/documentation_site/.gitignore
  upwork-devs/ashish-belwase/documentation_site/LICENSE
  upwork-devs/ashish-belwase/documentation_site/README.md
  upwork-devs/ashish-belwase/documentation_site/gatsby-browser.js
  upwork-devs/ashish-belwase/documentation_site/gatsby-config.js
  upwork-devs/ashish-belwase/documentation_site/gatsby-node.js
  upwork-devs/ashish-belwase/documentation_site/gatsby-ssr.js
  upwork-devs/ashish-belwase/documentation_site/package-lock.json
  upwork-devs/ashish-belwase/documentation_site/package.json
  upwork-devs/ashish-belwase/documentation_site/src/components/header.js
  upwork-devs/ashish-belwase/documentation_site/src/components/image.js
  upwork-devs/ashish-belwase/documentation_site/src/components/layout.css
  upwork-devs/ashish-belwase/documentation_site/src/components/layout.js
  upwork-devs/ashish-belwase/documentation_site/src/components/seo.js
  upwork-devs/ashish-belwase/documentation_site/src/images/gatsby-astronaut.png
  upwork-devs/ashish-belwase/documentation_site/src/images/gatsby-icon.png
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/ashish-belwase/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/faisal-adnan/Artillery/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/faisal-adnan/JMeter/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/faisal-adnan/Minio/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/faisal-adnan/PacketBeat/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/faisal-adnan/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/harut-gigoryan/logio-poc/HOWTO.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/pranay-sahith/opencensus_poc/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/pranay-sahith/test_orchestrator/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/susanta-gautam/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/yarden-shoham/README.md
  upwork-devs/ashish-belwase/documentation_site/src/k8-traffic-generator-master/upwork-devs/yarden-shoham/chart/README.md
  upwork-devs/ashish-belwase/documentation_site/src/pages/404.js
  upwork-devs/ashish-belwase/documentation_site/src/pages/index.js
  upwork-devs/ashish-belwase/documentation_site/src/pages/using-typescript.tsx
  upwork-devs/ashish-belwase/documentation_site/src/templates/main.css
  upwork-devs/ashish-belwase/documentation_site/src/templates/markdownTemplate.js
Labels: ready-for-review

#75 update / uploading file
  upwork-devs/golang_rs/config.toml
  upwork-devs/golang_rs/config/config.go
  upwork-devs/golang_rs/generateurl/generateurl.go
  upwork-devs/golang_rs/log/log.go
  upwork-devs/golang_rs/main.go
  upwork-devs/golang_rs/screenshot/screenshot.go
  upwork-devs/golang_rs/timeresponse/time.go
  upwork-devs/golang_rs/upload.html
  upwork-devs/golang_rs/upload/uploadfile.go
  upwork-devs/golang_rs/urltxt.txt
Labels: ready-for-review

#76 Traffic generator with Next cloud [POC]
  upwork-devs/pranay-sahith/next_cloud/Dockerfile
  upwork-devs/pranay-sahith/next_cloud/README.md
  upwork-devs/pranay-sahith/next_cloud/docker-compose.yaml
  upwork-devs/pranay-sahith/next_cloud/main.py
  upwork-devs/pranay-sahith/next_cloud/nextcloud.values.yml
  upwork-devs/pranay-sahith/next_cloud/opencensus_prometheus.py
  upwork-devs/pranay-sahith/next_cloud/requirements.txt
  upwork-devs/pranay-sahith/next_cloud/traffic_generator.py
  upwork-devs/pranay-sahith/next_cloud/traffic_generator.yaml
Labels: ready-for-review

#77 Add ability to see pods in frontend
  upwork-devs/yarden-shoham/file-drop.co.uk/backend/backend/__main__.py
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/package-lock.json
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/package.json
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/App.css
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/App.js
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/components/FileUploader.jsx
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/components/JobDeleter.jsx
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/components/PodViewer.jsx
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/index.js
Labels: ready-for-review

#88 Traffic generation and file validation for gov.uk
  .gitignore
  upwork-devs/pranay-sahith/gov-uk/Dockerfile
  upwork-devs/pranay-sahith/gov-uk/README.md
  upwork-devs/pranay-sahith/gov-uk/docker-compose.yaml
  upwork-devs/pranay-sahith/gov-uk/entrypoint.sh
  upwork-devs/pranay-sahith/gov-uk/gov-uk_job.yaml
  upwork-devs/pranay-sahith/gov-uk/gw_file_drop.py
  upwork-devs/pranay-sahith/gov-uk/main.py
  upwork-devs/pranay-sahith/gov-uk/requirements.txt
  upwork-devs/pranay-sahith/gov-uk/tests/test_gov_uk.py
  upwork-devs/pranay-sahith/gov-uk/traffic_generator.py
Labels: ready-for-review

#89 Traffic Generator against gov.uk
  upwork-devs/susanta-gautam/minio-traffic-generator/.dockerignore
  upwork-devs/susanta-gautam/minio-traffic-generator/Dockerfile
  upwork-devs/susanta-gautam/minio-traffic-generator/README.md
  upwork-devs/susanta-gautam/minio-traffic-generator/doc-image/flow.png
  upwork-devs/susanta-gautam/minio-traffic-generator/docker-compose.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/README.md
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/gateway.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/ingress.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/minio-deployment.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/nodeport.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/service.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/minio/virtualservice.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/miniotraffic-deployment.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/miniotrafic-job.yaml
  upwork-devs/susanta-gautam/minio-traffic-generator/requirement.txt
  upwork-devs/susanta-gautam/minio-traffic-generator/target_minio.py
  upwork-devs/susanta-gautam/traffic-against-gov.uk/.dockerignore
  upwork-devs/susanta-gautam/traffic-against-gov.uk/Dockerfile
  upwork-devs/susanta-gautam/traffic-against-gov.uk/README.md
  upwork-devs/susanta-gautam/traffic-against-gov.uk/doc-image/traffic-generator-gov-uk.png
  upwork-devs/susanta-gautam/traffic-against-gov.uk/jobmanifest.yaml
  upwork-devs/susanta-gautam/traffic-against-gov.uk/package.json
  upwork-devs/susanta-gautam/traffic-against-gov.uk/src/functions.js
  upwork-devs/susanta-gautam/traffic-against-gov.uk/src/index.js
  upwork-devs/susanta-gautam/traffic-against-gov.uk/src/logger.js
  upwork-devs/susanta-gautam/traffic-against-gov.uk/src/puppeteer.js
Labels: ready-for-review

#85 Rename golang_rs to golang-rs
  upwork-devs/golang-rs/config.toml
  upwork-devs/golang-rs/config/config.go
  upwork-devs/golang-rs/generateurl/generateurl.go
  upwork-devs/golang-rs/log/log.go
  upwork-devs/golang-rs/main.go
  upwork-devs/golang-rs/screenshot/screenshot.go
  upwork-devs/golang-rs/timeresponse/time.go
  upwork-devs/golang-rs/upload.html
  upwork-devs/golang-rs/upload/uploadfile.go
  upwork-devs/golang-rs/urltxt.txt
Labels: ready-for-review

#87 Use fetch instead of axios
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/package.json
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/components/JobDeleter.jsx
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/src/components/PodViewer.jsx
Labels: ready-for-review

#94 Fix vulnerability issues
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/package-lock.json
  upwork-devs/yarden-shoham/file-drop.co.uk/frontend/yarn.lock
Labels: ready-for-review

#96 Create a demo of tracing http calls from/to pods
  upwork-devs/Roozbeh-Moayydeian/Installation/basic-dep.yaml
  upwork-devs/Roozbeh-Moayydeian/Installation/setup-grafana.yaml
  upwork-devs/Roozbeh-Moayydeian/Installation/setup-istio.yaml
  upwork-devs/Roozbeh-Moayydeian/Installation/setup-jaeger.yaml
  upwork-devs/Roozbeh-Moayydeian/Installation/setup-kiali.yaml
  upwork-devs/Roozbeh-Moayydeian/Installation/setup-prometheus.yaml
  upwork-devs/Roozbeh-Moayydeian/LoadGenerator/Dockerfile
  upwork-devs/Roozbeh-Moayydeian/LoadGenerator/index.js
  upwork-devs/Roozbeh-Moayydeian/LoadGenerator/input.json
  upwork-devs/Roozbeh-Moayydeian/LoadGenerator/package.json
  upwork-devs/Roozbeh-Moayydeian/README.md
  upwork-devs/Roozbeh-Moayydeian/img/0replica/1-rancher.png
  upwork-devs/Roozbeh-Moayydeian/img/0replica/2-lg-deployment.png
  upwork-devs/Roozbeh-Moayydeian/img/0replica/3-nginx-pod.png
  upwork-devs/Roozbeh-Moayydeian/img/0replica/4-kiali.png
  upwork-devs/Roozbeh-Moayydeian/img/0replica/5-istio.png
  upwork-devs/Roozbeh-Moayydeian/img/1replica/1-rancher.png
  upwork-devs/Roozbeh-Moayydeian/img/1replica/2-lg-deployment.png
  upwork-devs/Roozbeh-Moayydeian/img/1replica/3-nginx-pod.png
  upwork-devs/Roozbeh-Moayydeian/img/1replica/4-kiali.png
  upwork-devs/Roozbeh-Moayydeian/img/1replica/5-istio.png
  upwork-devs/Roozbeh-Moayydeian/img/2replica/1-rancher.png
  upwork-devs/Roozbeh-Moayydeian/img/2replica/2-lg-deployment.png
  upwork-devs/Roozbeh-Moayydeian/img/2replica/3-nginx-pod.png
  upwork-devs/Roozbeh-Moayydeian/img/2replica/4-kiali.png
  upwork-devs/Roozbeh-Moayydeian/img/2replica/5-istio.png
  upwork-devs/Roozbeh-Moayydeian/img/3replica/1-rancher.png
  upwork-devs/Roozbeh-Moayydeian/img/3replica/2-lg-deployment.png
  upwork-devs/Roozbeh-Moayydeian/img/3replica/3-nginx-pod.png
  upwork-devs/Roozbeh-Moayydeian/img/3replica/4-kiali.png
  upwork-devs/Roozbeh-Moayydeian/img/3replica/5-istio.png
  upwork-devs/Roozbeh-Moayydeian/img/diagram.png
  upwork-devs/Roozbeh-Moayydeian/img/grafana1.png
  upwork-devs/Roozbeh-Moayydeian/img/grafana2.png
  upwork-devs/Roozbeh-Moayydeian/img/grafana3.png
  upwork-devs/Roozbeh-Moayydeian/img/jaeger.png
  upwork-devs/Roozbeh-Moayydeian/img/kiali.png
  upwork-devs/Roozbeh-Moayydeian/img/rancher.png
  upwork-devs/Roozbeh-Moayydeian/load-generator-dep.yaml
  upwork-devs/Roozbeh-Moayydeian/net-tools-dep.yaml
  upwork-devs/Roozbeh-Moayydeian/nginx-dep.yaml
Labels: changes-requested

#98 Create a documentation to setup ELK, Minio, JMeter, and Artillery using minikube on Windows 10Win10 doc
  docs/Win10.md
Labels: ready-for-review

#102 Issue99 powershell scripts
  upwork-devs/faisal-adnan/Artillery/README.md
  upwork-devs/faisal-adnan/Artillery/run.ps1
  upwork-devs/faisal-adnan/JMeter/README.md
  upwork-devs/faisal-adnan/JMeter/run.ps1
Labels: ready-for-review

#103 Send test results to Elastic
  upwork-devs/pranay-sahith/gov-uk/README.md
  upwork-devs/pranay-sahith/gov-uk/docker-compose.yaml
  upwork-devs/pranay-sahith/gov-uk/elastic_service.py
  upwork-devs/pranay-sahith/gov-uk/gov-uk_job.yaml
  upwork-devs/pranay-sahith/gov-uk/requirements.txt
  upwork-devs/pranay-sahith/gov-uk/tests/test_gov_uk.py
Labels: ready-for-review

#100 Local rebuild
  upwork-devs/yarden-shoham/local-rebuild/chart/Chart.yaml
  upwork-devs/yarden-shoham/local-rebuild/chart/templates/job.yaml
  upwork-devs/yarden-shoham/local-rebuild/chart/values.yaml
  upwork-devs/yarden-shoham/local-rebuild/dispatcher/.dockerignore
  upwork-devs/yarden-shoham/local-rebuild/dispatcher/Dockerfile
  upwork-devs/yarden-shoham/local-rebuild/dispatcher/README.md
  upwork-devs/yarden-shoham/local-rebuild/dispatcher/dispatcher/__init__.py
  upwork-devs/yarden-shoham/local-rebuild/dispatcher/dispatcher/__main__.py
  upwork-devs/yarden-shoham/local-rebuild/dispatcher/requirements.txt
  upwork-devs/yarden-shoham/local-rebuild/downloader/.dockerignore
  upwork-devs/yarden-shoham/local-rebuild/downloader/Dockerfile
  upwork-devs/yarden-shoham/local-rebuild/downloader/README.md
  upwork-devs/yarden-shoham/local-rebuild/downloader/docker-entrypoint.sh
Labels: ready-for-review

#120 Fix github actions
  .github/workflows/sast.yml
  .github/workflows/sca.yml
  .github/workflows/secret.yml
Labels: ready-for-review

#113 ELK + metricbeat for the visualization of the clusterhealth.
  upwork-devs/susanta-gautam/metricbeats-elk/README.md
  upwork-devs/susanta-gautam/metricbeats-elk/helm-elasticsearch/values.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kibana-ingress/disable-mtls.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kibana-ingress/kibana-gateway.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kibana-ingress/kibana-virtualservice.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kube-state-metrics/cluster-role-binding.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kube-state-metrics/cluster-role.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kube-state-metrics/deployment.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kube-state-metrics/service-account.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/kube-state-metrics/service.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/metricsbeats/clusterRole.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/metricsbeats/metricbeat-deployment-with-dashboard.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/metricsbeats/metricbeat-deployment.yaml
  upwork-devs/susanta-gautam/metricbeats-elk/metricsbeats/metricsbeats-daemonset.yaml
Labels: ready-for-review

#117 Use the Rebuild engine as the target system #58
  upwork-devs/harut-gigoryan/rebuild-engine/README.md
  upwork-devs/harut-gigoryan/rebuild-engine/all-in-one.yaml
  upwork-devs/harut-gigoryan/rebuild-engine/elk.yaml
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/.dockerignore
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/Dockerfile
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/Makefile
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/filebeat.yml
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/inspector.py
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/logging.conf
  upwork-devs/harut-gigoryan/rebuild-engine/inspector/requirement.txt
  upwork-devs/harut-gigoryan/rebuild-engine/minio.yaml
  upwork-devs/harut-gigoryan/rebuild-engine/processor/.dockerignore
  upwork-devs/harut-gigoryan/rebuild-engine/processor/Dockerfile
  upwork-devs/harut-gigoryan/rebuild-engine/processor/Makefile
  upwork-devs/harut-gigoryan/rebuild-engine/processor/filebeat.yml
  upwork-devs/harut-gigoryan/rebuild-engine/processor/logging.conf
  upwork-devs/harut-gigoryan/rebuild-engine/processor/processor-deployment.yaml
  upwork-devs/harut-gigoryan/rebuild-engine/processor/processor.py
  upwork-devs/harut-gigoryan/rebuild-engine/processor/requirement.txt
Labels: ready-for-review

#118 Local rebuild argo
  upwork-devs/yarden-shoham/local-rebuild-argo/README.md
  upwork-devs/yarden-shoham/local-rebuild-argo/lister/.dockerignore
  upwork-devs/yarden-shoham/local-rebuild-argo/lister/Dockerfile
  upwork-devs/yarden-shoham/local-rebuild-argo/lister/lister/__init__.py
  upwork-devs/yarden-shoham/local-rebuild-argo/lister/lister/__main__.py
  upwork-devs/yarden-shoham/local-rebuild-argo/lister/requirements.txt
  upwork-devs/yarden-shoham/local-rebuild-argo/workflow.yaml
Labels: ready-for-review

#122 Fix local rebuild argo typo
  upwork-devs/yarden-shoham/local-rebuild-argo/README.md
Labels: ready-for-review

#123 Remove unused volume in workflow
  upwork-devs/yarden-shoham/local-rebuild-argo/workflow.yaml
Labels: ready-for-review

#129 Create a demo of access.log visualisation using ELK
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/README.md
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/diagram.xml
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/docker-compose.yml
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/fluentd/Dockerfile
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/fluentd/conf/fluent.conf
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/howIstioProxyWorks.png
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/howNginxReverseProxyWorks.png
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/jmeter/glasswallsolutions.local.jmx
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/jmeter/results/results.csv
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/nginx/conf.d/default.conf
  upwork-devs/Roozbeh-Moayydeian/jmeter-efk/nginx/nginx.conf
  upwork-devs/Roozbeh-Moayydeian/load-generator-dep.yaml
Labels: ready-for-review

#78 feat: context, container, gui and controller component diagrams
  upwork-devs/a-khaledf/container.png
  upwork-devs/a-khaledf/container.puml
  upwork-devs/a-khaledf/context.png
  upwork-devs/a-khaledf/context.puml
  upwork-devs/a-khaledf/controller_component.png
  upwork-devs/a-khaledf/controller_component.puml
  upwork-devs/a-khaledf/gui_component.png
  upwork-devs/a-khaledf/gui_component.puml
Labels: discuss-in-slack

#133 Local Rebuild Argo Elasticsearch
  upwork-devs/yarden-shoham/local-rebuild-argo/README.md
  upwork-devs/yarden-shoham/local-rebuild-argo/uploader/.dockerignore
  upwork-devs/yarden-shoham/local-rebuild-argo/uploader/Dockerfile
  upwork-devs/yarden-shoham/local-rebuild-argo/uploader/requirements.txt
  upwork-devs/yarden-shoham/local-rebuild-argo/uploader/uploader/__init__.py
  upwork-devs/yarden-shoham/local-rebuild-argo/uploader/uploader/__main__.py
  upwork-devs/yarden-shoham/local-rebuild-argo/workflow.yaml
Labels: ready-for-review

#131 fix bandit issues
  upwork-devs/Roozbeh-Moayydeian/README.md
  upwork-devs/Roozbeh-Moayydeian/load-generator-dep.yaml
  upwork-devs/Roozbeh-Moayydeian/net-tools-dep.yaml
  upwork-devs/Roozbeh-Moayydeian/nginx-dep.yaml
  upwork-devs/pranay-sahith/gov-uk/traffic_generator.py
  upwork-devs/pranay-sahith/opencensus_poc/traffic_generator.py
Labels: ready-for-review

#134 Fix bandit issues
  upwork-devs/ashish-belwase/helper.py
  upwork-devs/yarden-shoham/file-drop.co.uk/backend/backend/__main__.py
  upwork-devs/yarden-shoham/file-drop.co.uk/processor/processor/__main__.py
Labels: ready-for-review

#135 Create Amazon Image
  upwork-devs/Roozbeh-Moayydeian/AMI/README.md
  upwork-devs/Roozbeh-Moayydeian/AMI/UserData.sh
  upwork-devs/Roozbeh-Moayydeian/AMI/create-ami-skeleton-example.json
  upwork-devs/Roozbeh-Moayydeian/AMI/create-ami-skeleton.json
  upwork-devs/Roozbeh-Moayydeian/AMI/createAMI.sh
  upwork-devs/Roozbeh-Moayydeian/AMI/run-instances-skeleton-example.json
  upwork-devs/Roozbeh-Moayydeian/AMI/run-instances-skeleton-out.json
  upwork-devs/Roozbeh-Moayydeian/AMI/run-instances-skeleton.json
Labels: ready-for-review
