Repository k8-proxy/k8-traffic-generator, pull requests merged in 2020-08, with the labels that each got.

#3 F/initial structure
  .gitignore
  ashish_belwase/Dockerfile
  ashish_belwase/README.md
  ashish_belwase/deploy.yaml
  ashish_belwase/helper.py
  ashish_belwase/main.py
  ashish_belwase/requirements.txt
  ashish_belwase/sites/base.py
  ashish_belwase/sites/glasswall.py
  ashish_belwase/traffic_generator.py
Labels: changes-requested

#1 Initial commits
  .gitignore
  upwork-devs/yarden-shoham/.dockerignore
  upwork-devs/yarden-shoham/Dockerfile
  upwork-devs/yarden-shoham/README.md
  upwork-devs/yarden-shoham/chart/.helmignore
  upwork-devs/yarden-shoham/chart/Chart.yaml
  upwork-devs/yarden-shoham/chart/README.md
  upwork-devs/yarden-shoham/chart/templates/_helpers.tpl
  upwork-devs/yarden-shoham/chart/templates/deployment.yaml
  upwork-devs/yarden-shoham/chart/templates/hpa.yaml
  upwork-devs/yarden-shoham/chart/templates/ingress.yaml
  upwork-devs/yarden-shoham/chart/templates/service.yaml
  upwork-devs/yarden-shoham/chart/templates/serviceaccount.yaml
  upwork-devs/yarden-shoham/chart/values.yaml
  upwork-devs/yarden-shoham/package-lock.json
  upwork-devs/yarden-shoham/package.json
  upwork-devs/yarden-shoham/src/index.js
  upwork-devs/yarden-shoham/src/interaction.js
  upwork-devs/yarden-shoham/src/interactionsWithNames.js
  upwork-devs/yarden-shoham/src/pdfTest.js
  upwork-devs/yarden-shoham/src/utils.js
Labels: ready-for-review

#21 Updated Artillery and JMeter PoC
  .gitignore
  upwork-devs/faisal-adnan/Artillery/Dockerfile
  upwork-devs/faisal-adnan/Artillery/README.md
  upwork-devs/faisal-adnan/Artillery/artillery-conf.yml
  upwork-devs/faisal-adnan/Artillery/artillery-job.yaml
  upwork-devs/faisal-adnan/Artillery/artillery-pod.yaml
  upwork-devs/faisal-adnan/JMeter/Dockerfile
  upwork-devs/faisal-adnan/JMeter/README.md
  upwork-devs/faisal-adnan/JMeter/gws.jmx
  upwork-devs/faisal-adnan/JMeter/jmeterjob.yaml
  upwork-devs/faisal-adnan/PacketBeat/README.md
Labels: ready-for-review

#24 Format tpl better
  upwork-devs/yarden-shoham/chart/templates/_helpers.tpl
Labels: ready-for-review

#25 Add pricing interactions
  upwork-devs/yarden-shoham/src/interactionsWithNames.js
  upwork-devs/yarden-shoham/src/pricingColumnCountTest.js
  upwork-devs/yarden-shoham/src/pricingCountTest.js
Labels: ready-for-review

#28 Added more action on glasswall, unit tests, elk config
  ashish_belwase/README.md
  ashish_belwase/elk_tenant.yml
  ashish_belwase/requirements.txt
  ashish_belwase/sites/base.py
  ashish_belwase/sites/glasswall.py
  ashish_belwase/tests/__init__.py
  ashish_belwase/tests/test_glasswall.py
  ashish_belwase/tests/test_main.py
  ashish_belwase/traffic_generator.py
Labels: ready-for-review

#30 Add a random click interaction and decrease delay between interactions
  upwork-devs/yarden-shoham/README.md
  upwork-devs/yarden-shoham/src/interaction.js
  upwork-devs/yarden-shoham/src/interactionsWithNames.js
  upwork-devs/yarden-shoham/src/pdfTest.js
  upwork-devs/yarden-shoham/src/randomClickInteraction.js
Labels: ready-for-review

#31 Delete roles-and-responsibilities.md
  roles-and-responsibilities.md
Labels: ready-for-review

#32 [FAD] Added Minio
  upwork-devs/faisal-adnan/Minio/README.md
  upwork-devs/faisal-adnan/Minio/minio.png
Labels: ready-for-review

#36 Shell script to deploy multiple traffic generator pods in multiple namespaces and generate traffic for a given duration
  .gitignore
  upwork-devs/pranaysahith/test_orchestrator/README.md
  upwork-devs/pranaysahith/test_orchestrator/chart/.gitignore
  upwork-devs/pranaysahith/test_orchestrator/chart/.helmignore
  upwork-devs/pranaysahith/test_orchestrator/chart/Chart.yaml
  upwork-devs/pranaysahith/test_orchestrator/chart/templates/_helpers.tpl
  upwork-devs/pranaysahith/test_orchestrator/chart/templates/deployment.yaml
  upwork-devs/pranaysahith/test_orchestrator/chart/templates/hpa.yml
  upwork-devs/pranaysahith/test_orchestrator/chart/templates/ingress.yaml
  upwork-devs/pranaysahith/test_orchestrator/chart/templates/secrets.yaml
  upwork-devs/pranaysahith/test_orchestrator/chart/templates/service.yaml
  upwork-devs/pranaysahith/test_orchestrator/chart/values.yaml
  upwork-devs/pranaysahith/test_orchestrator/test.sh
Labels: ready-for-review

#39 Consolidate upwork-devs
  upwork-devs/ashish-belwase/Dockerfile
  upwork-devs/ashish-belwase/README.md
  upwork-devs/ashish-belwase/deploy.yaml
  upwork-devs/ashish-belwase/elk_tenant.yml
  upwork-devs/ashish-belwase/helper.py
  upwork-devs/ashish-belwase/main.py
  upwork-devs/ashish-belwase/requirements.txt
  upwork-devs/ashish-belwase/sites/base.py
  upwork-devs/ashish-belwase/sites/glasswall.py
  upwork-devs/ashish-belwase/tests/__init__.py
  upwork-devs/ashish-belwase/tests/test_glasswall.py
  upwork-devs/ashish-belwase/tests/test_main.py
  upwork-devs/ashish-belwase/traffic_generator.py
  upwork-devs/pranay-sahith/opencensus_poc/.dockerignore
  upwork-devs/pranay-sahith/opencensus_poc/Dockerfile
  upwork-devs/pranay-sahith/opencensus_poc/README.md
  upwork-devs/pranay-sahith/opencensus_poc/docker-compose.yaml
  upwork-devs/pranay-sahith/opencensus_poc/main.py
  upwork-devs/pranay-sahith/opencensus_poc/opencensus_prometheus.py
  upwork-devs/pranay-sahith/opencensus_poc/requirements.txt
  upwork-devs/pranay-sahith/opencensus_poc/traffic_generator.py
  upwork-devs/pranay-sahith/opencensus_poc/traffic_generator.yaml
  upwork-devs/pranay-sahith/test_orchestrator/README.md
  upwork-devs/pranay-sahith/test_orchestrator/chart/.gitignore
  upwork-devs/pranay-sahith/test_orchestrator/chart/.helmignore
  upwork-devs/pranay-sahith/test_orchestrator/chart/Chart.yaml
  upwork-devs/pranay-sahith/test_orchestrator/chart/templates/_helpers.tpl
  upwork-devs/pranay-sahith/test_orchestrator/chart/templates/deployment.yaml
  upwork-devs/pranay-sahith/test_orchestrator/chart/templates/hpa.yml
  upwork-devs/pranay-sahith/test_orchestrator/chart/templates/ingress.yaml
  upwork-devs/pranay-sahith/test_orchestrator/chart/templates/secrets.yaml
  upwork-devs/pranay-sahith/test_orchestrator/chart/templates/service.yaml
  upwork-devs/pranay-sahith/test_orchestrator/chart/values.yaml
  upwork-devs/pranay-sahith/test_orchestrator/test.sh
Labels: ready-for-review

#33 Traffic Generated against Minio.
  upwork-devs/susanta-gautam/.dockerignore
  upwork-devs/susanta-gautam/Dockerfile
  upwork-devs/susanta-gautam/README.md
  upwork-devs/susanta-gautam/doc-image/flow.png
  upwork-devs/susanta-gautam/docker-compose.yaml
  upwork-devs/susanta-gautam/miniotraffic-deployment.yaml
  upwork-devs/susanta-gautam/miniotrafic-job.yaml
  upwork-devs/susanta-gautam/requirement.txt
  upwork-devs/susanta-gautam/target_minio.py
Labels: admin-needed, ready-for-review

#42 Add helm chart installation instructions to README.md
  upwork-devs/yarden-shoham/README.md
  upwork-devs/yarden-shoham/chart/templates/_helpers.tpl
Labels: ready-for-review
